Feature/coredata refactor
boostcamp3-iOS/team-a1 pull request #102
Opened 2019-02-23 10:46 UTC by onemoongit

3개의 구조에 대한 코어데이터 수정 그리고 web관련 스크랩 기능 구현입니다
- webView Article
- webNativeVieer Article
- SearchedArticle 

또한 라이브 카테고리가 추가되었습니다.

2019-02-23 11:18 UTC, kimhyeri reviewed
리펙토링 고생 많으셨어여

2019-02-23 11:18 UTC, kimhyeri commented on tree/tree/Controller/Search/ArticleViewer/ArticleDetailViewController.swift
> +    var press: String?
press를 조금 디테일한 변수명으로 바꿔주는건 어떨까요?

2019-02-23 11:18 UTC, kimhyeri commented on tree/tree/Controller/Search/ArticleViewer/ArticleWebViewController.swift
> +//    private func makeURLRequest(urlString: String) -> URLRequest? {
이 부분은 지워주시면 감사하겠습니다...ㅎ!

2019-02-23 11:18 UTC, kimhyeri commented on tree/tree/Model/DataManager/ScrappedArticleStruct.swift
> +public enum ScrappedArticleType: CaseIterable {
오호 이렇게 하셨군요 ! 굳

2019-02-23 13:13 UTC, godpp reviewed
고생하셨습니다! 👍 

코멘트 확인 부탁드려요! 👍 👍 👍

2019-02-23 13:13 UTC, godpp commented on tree/tree/Controller/Scrap/ScrapViewController.swift
> +        guard let articleTypeString = scrappedArticle.articleType else { return UITableViewCell() }
튜터님이 저번에 알려주신 방법으로 빈 Cell로 만드는 것보다 fatalError나 precondition으로 종료시켜주는 방법은 어떠신가요?

2019-02-23 13:13 UTC, godpp commented on tree/tree/Controller/Scrap/ScrapViewController.swift
> +            let storyboard = UIStoryboard(name: "ArticleDetail", bundle: nil)
세 곳에서 쓰이는 것 같은데 위로 빼셔도 될 것 같습니다! 👍

2019-02-23 15:28 UTC, yagom requested changes

2019-02-23 15:28 UTC, yagom commented on tree/tree/Controller/Search/ArticleViewer/ArticleDetailViewController.swift
> +    private func setupScrapButton() {
scrapButton을 IBOutlet으로 연결해줬고, IBAction으로 연결해 줄 수 있는데 굳이 이렇게 처리한 이유가 궁금하네요

2019-02-23 15:28 UTC, yagom commented on tree/tree/Controller/Search/ArticleViewer/ArticleWebViewController.swift
> +    private func loadWebDataWithURL() {
무슨 URL일지 알 수 있어야 하지 않을까요? 정 어렵다면 매개변수로 받을 수도 있고요

2019-02-23 15:28 UTC, yagom commented on tree/tree/Controller/Search/ArticleViewer/ArticleWebViewController.swift
> +//    private func loadWebView() {
??

2019-02-24 02:51 UTC, onemoongit commented on tree/tree/Controller/Search/ArticleViewer/ArticleWebViewController.swift
> +//    private func makeURLRequest(urlString: String) -> URLRequest? {
코멘트 감사합니다! 빼먹었네요!

2019-02-24 02:55 UTC, onemoongit commented on tree/tree/Controller/Search/ArticleViewer/ArticleDetailViewController.swift
> +    var press: String?
넵 변경했습니다 감사합니다 !! 👍

2019-02-24 02:58 UTC, onemoongit commented on tree/tree/Controller/Scrap/ScrapViewController.swift
> +        guard let articleTypeString = scrappedArticle.articleType else { return UITableViewCell() }
네 어차피 표현이 안되니 fatalError 로 표현하는게 나을것 같습니다! 좋은 의견 감사합니다! 💯

2019-02-24 03:07 UTC, onemoongit commented on tree/tree/Controller/Search/ArticleViewer/ArticleDetailViewController.swift
> +    private func setupScrapButton() {
저는 iboutlet 을 연결한다면 해당 outlet에 코드로 함수를 추가하는것이 더 명시적이라고 생각해서 이렇게 작성했습니다!
동일한 타겟에 대해서 iboutlet과 ibaction을 둘다 처리하게 된다면 스토리보드에서 두번 연결해줘야 하고, 네이밍을 동일하게 하더라도 혹시 다른 타겟이라고 생각할 수도 있지 않을까 라는 생각에 저는 iboutlet에는 addTarget을 선호는 편입니다. 
혹시 제가 생각하지 못한 다른 이슈가 있을까요?!

2019-02-24 03:15 UTC, onemoongit commented on tree/tree/Controller/Search/ArticleViewer/ArticleWebViewController.swift
> +    private func loadWebDataWithURL() {
넵 생각해보니 저는 당연히 클래스내의 URL 을 받는 함수라고 생각했는데 너무 제입장에서 작성한 코드인것 같습니다! 변수로 URL을 받도록 수정하였습니다! 
좋은 지적 감사합니다!! 💯

2019-02-24 03:15 UTC, onemoongit commented on tree/tree/Controller/Search/ArticleViewer/ArticleWebViewController.swift
> +//    private func loadWebView() {
많은양의 주석들을 지우다보니 실수로 못지웠습니다 😢 바로 수정하였습니다!!

2019-02-24 03:32 UTC, onemoongit commented on tree/tree/Controller/Scrap/ScrapViewController.swift
> +            let storyboard = UIStoryboard(name: "ArticleDetail", bundle: nil)
제가 빼먹었네요! 좋은 지적 감사합니다 !! 👍

2019-02-24 04:40 UTC, yagom commented on tree/tree/Controller/Search/ArticleViewer/ArticleDetailViewController.swift
> +    private func setupScrapButton() {
> 동일한 타겟에 대해서 iboutlet과 ibaction을 둘다 처리하게 된다면 스토리보드에서 두번 연결해줘야 하고, 네이밍을 동일하게 하더라도 혹시 다른 타겟이라고 생각할 수도 있지 않을까 라는 생각

이 무슨 뜻인지 잘 모르겠습니다 다른 모둠원들은 어떻게 생각하는지 의견 묻고 싶습니다. @godpp @kimhyeri

2019-02-24 05:04 UTC, godpp approved these changes
👍 👍 👍

2019-02-24 05:49 UTC, godpp commented on tree/tree/Controller/Search/ArticleViewer/ArticleDetailViewController.swift
> +    private func setupScrapButton() {
@yagom 저는 IBAction이 특정한 상황에서 유연성을 가지지 못하는 경우도 있기 때문에 주로 addTarget을 사용하고 있습니다. 그래서 코드의 일정한 컨밴션과 개인적인 습관(?)때문에 UIBarButtonItem과 같이 addTarget이 불가능한 경우가 아닐때만 IBAction을 사용하고 있습니다.

그런데 튜터님의 말씀대로 한다면 표현되는 방식이 더 명확해 질 것 같다는 생각이 들었습니다.

2019-02-24 06:18 UTC, yagom commented on tree/tree/Controller/Search/ArticleViewer/ArticleDetailViewController.swift
> +    private func setupScrapButton() {
@godpp 그렇군요 그치만 조금 다른 이야기를 해보자면 UIBarButtonItem도 코드로 target과 action 지정이 가능합니다

2019-02-24 06:20 UTC, yagom commented on tree/tree/Controller/Search/ArticleViewer/ArticleDetailViewController.swift
> +    private func setupScrapButton() {
@onemoongit 선호도의 다름이기 때문에 틀린 것은 아닙니다. 적절한 본인의 이유가 있고 팀끼리 협의가 되어있다면 일단 approve!

2019-02-24 06:20 UTC, yagom approved these changes

2019-02-24 06:24 UTC, godpp commented on tree/tree/Controller/Search/ArticleViewer/ArticleDetailViewController.swift
> +    private func setupScrapButton() {
@yagom 헙 target action 따로 따로 지정이 가능한지는 몰랐습니다...

2019-02-24 06:25 UTC, kimhyeri approved these changes

2019-02-24 06:28 UTC, merged