Feature/live feed
boostcamp3-iOS/team-a1 pull request #72
Opened 2019-02-12 08:05 UTC by kimhyeri

- articleFeed 동적인 높이에서 reload 버그 해결
- imageCache 타입 나누기
- 아티클 스크랩 작업 가능하도록 함 (swiping cell)

2019-02-12 08:28 UTC, godpp requested changes
수고하셨습니다 👍 
리뷰 피드백 부탁드립니다! 👍

2019-02-12 08:28 UTC, godpp commented on tree/tree/Controller/Search/SearchViewController.swift
> +            if scrollPosition > 0 && scrollPosition < scrollView.contentSize.height * 0.2 {
스크롤뷰 포지션이 0이상 높이 * 0.2 이하 같은데, 이 조건문은 함수로 빼서 하나의 이름으로 만드는게 낫지 않을까요?!?!?

2019-02-12 08:28 UTC, godpp commented on tree/tree/Controller/Search/SearchViewController.swift
> +        } else {
else는 필요없지 않을까요?! 👍

2019-02-12 08:28 UTC, godpp commented on tree/tree/Controller/Search/SearchViewController.swift
> +                for: indexPath) as? ArticleFeedTableViewCell
) 이전에 한번 더 줄바꿈 부탁드릴게요!

2019-02-12 08:28 UTC, godpp commented on tree/tree/Controller/Search/ArticleImageViewController.swift
> +        } else if sender.state == UIGestureRecognizer.State.ended ||
switch case문이 가독성이 더 높을 것 같은데 어떻게 생각하시나요?!?! 😄

2019-02-12 08:28 UTC, godpp commented on tree/tree/Extension/Extension+ImageView.swift
> +            if let imagePath = imageCache.path(for: extract ?? ""),
if let 구문에 ?? default 값을 지정해줄 필요가 없어보입니다! 👍

2019-02-12 08:36 UTC, kimhyeri commented on tree/tree/Controller/Search/ArticleImageViewController.swift
> +        } else if sender.state == UIGestureRecognizer.State.ended ||
너무 좋습니다.

2019-02-12 08:37 UTC, kimhyeri commented on tree/tree/Controller/Search/SearchViewController.swift
> +                for: indexPath) as? ArticleFeedTableViewCell
넵 !

2019-02-12 08:40 UTC, kimhyeri commented on tree/tree/Controller/Search/SearchViewController.swift
> +        } else {
아이가릿

2019-02-12 08:51 UTC, kimhyeri commented on tree/tree/Controller/Search/SearchViewController.swift
> +            if scrollPosition > 0 && scrollPosition < scrollView.contentSize.height * 0.2 {
네 checkPosition으로 뽑겠습니다!

2019-02-12 08:59 UTC, kimhyeri commented on tree/tree/Extension/Extension+ImageView.swift
> +            if let imagePath = imageCache.path(for: extract ?? ""),
넵 default value제거했습니다!

2019-02-13 02:20 UTC, godpp approved these changes

2019-02-13 03:15 UTC, yagom reviewed
코멘트 확인 바랍니다

2019-02-13 03:15 UTC, yagom commented on tree/tree/Controller/Search/SearchViewController.swift
> +    func checkPosition(position: CGFloat, height: CGFloat) -> Bool {
메서드 이름을 좀 더 명확히 해보면 좋겠습니다

2019-02-13 03:15 UTC, yagom commented on tree/tree/Controller/Search/ArticleImageViewController.swift
> +        switch sender.state {
switch 사용 좋아요

2019-02-13 03:15 UTC, yagom commented on tree/tree/Controller/Search/SearchViewController.swift
> +        if position > 0 && position < height * 0.2 {
0.2는 어떤 의미로 사용했나요?

2019-02-13 03:32 UTC, kim-howard requested changes
저희 협업하기로 한 네이밍 변경해주시면 좋을 것 같습니다 ! 👍 
tableView swipe function 얼른 만들어드릴게요 !

2019-02-13 03:32 UTC, onemoongit commented on tree/tree/Helper/ImageCacheTypeEnum.swift
> +    case none
Enum 활용 아주 좋은것 같습니다 👍

2019-02-13 03:32 UTC, onemoongit commented on tree/tree/Controller/Search/SearchViewController.swift
>      private func searchBarSetting() {
전체적으로 Setup 으로 변경해주세요 ! 😭

2019-02-13 03:32 UTC, onemoongit commented on tree/tree/Controller/Search/SearchViewController.swift
> +    func tableView(_ tableView: UITableView, commit editingStyle: UITableViewCell.EditingStyle, forRowAt indexPath: IndexPath) {
이부분은 제가 관련된 함수를 만들어서 전달해드리겠습니다 👍

2019-02-13 03:51 UTC, kimhyeri commented on tree/tree/Controller/Search/SearchViewController.swift
> +    func checkPosition(position: CGFloat, height: CGFloat) -> Bool {
checkReload(position: ,height: )로 변경하겠습니다!

2019-02-13 03:52 UTC, kimhyeri commented on tree/tree/Controller/Search/ArticleImageViewController.swift
> +        switch sender.state {
😁

2019-02-13 04:03 UTC, yagom commented on tree/tree/Controller/Search/SearchViewController.swift
> +    func checkPosition(position: CGFloat, height: CGFloat) -> Bool {
저는 궁금한 것이 Bool을 반환해 주는데 check라는 단어가 의미에 맞을까 한 것이었습니다. Bool을 반환해 줄 때 쓸 수 있을만한 의미있는 단어가 무엇이 있을까요?

2019-02-13 04:06 UTC, kimhyeri commented on tree/tree/Controller/Search/SearchViewController.swift
> +        if position > 0 && position < height * 0.2 {
checkPosition은 스크롤을 할 때 어느 시점에서 데이터를 더 불러올지 위치를 체크해주는 함수로 사용했습니다.

checkPosition에서
- position은 scrollView.contentSize.height - scrollView.frame.size.height - scrollView.contentOffset.y 를 인자로 보내줍니다.
- height는 scrollView.contentSize.height로 인자를 보냅니다.

현재 position이 전체 컨텐츠(height)의 0.2 부분 보다 작게되면 데이터를 더 불러오도록 하려고  0.2라고 잡았습니다.

2019-02-13 04:07 UTC, kimhyeri commented on tree/tree/Helper/ImageCacheTypeEnum.swift
> +    case none
😆

2019-02-13 04:07 UTC, yagom commented on tree/tree/Controller/Search/SearchViewController.swift
> +        if position > 0 && position < height * 0.2 {
그러면 의미있는 상수로 이름을 붙여주고 쓰는 것이 더 좋지 않을까요?
minimumHeightPortionToLoadAdditionalData 등등.. (이름이 기네요;; 좀 더 고민해보면 좋을 듯)

2019-02-13 04:09 UTC, kimhyeri commented on tree/tree/Controller/Search/SearchViewController.swift
>      private func searchBarSetting() {
네 변경하겠습니다!

2019-02-13 04:10 UTC, kimhyeri commented on tree/tree/Controller/Search/SearchViewController.swift
> +    func tableView(_ tableView: UITableView, commit editingStyle: UITableViewCell.EditingStyle, forRowAt indexPath: IndexPath) {
넵 알겠습니당

2019-02-13 04:51 UTC, kimhyeri commented on tree/tree/Controller/Search/SearchViewController.swift
> +    func checkPosition(position: CGFloat, height: CGFloat) -> Bool {
찾아보니 Bool을 반환하면 is, does, will, can, should를 많이 사용하는것 같습니다.
isAdditionalDataPosition로 변경하겠습니다.

2019-02-13 04:53 UTC, yagom commented on tree/tree/Controller/Search/SearchViewController.swift
> +    func checkPosition(position: CGFloat, height: CGFloat) -> Bool {
shouldLoadAdditionalData는 어때요?

2019-02-13 04:54 UTC, kimhyeri commented on tree/tree/Controller/Search/SearchViewController.swift
> +        if position > 0 && position < height * 0.2 {
수정했습니다!
(상수명은 추천해주신걸로 작성했습니다. 괜찮은게 생각나면 수정하겠습니다. 😭)

2019-02-13 04:58 UTC, kimhyeri commented on tree/tree/Controller/Search/SearchViewController.swift
> +    func checkPosition(position: CGFloat, height: CGFloat) -> Bool {
네 좋아요 ㅠㅠ 흑 감사합니다!

2019-02-13 05:23 UTC, kim-howard approved these changes

2019-02-13 05:26 UTC, yagom commented
okay

2019-02-13 05:35 UTC, merged