Feature/live events
boostcamp3-iOS/team-a1 pull request #76
Opened 2019-02-15 05:25 UTC by godpp

아래 항목들 추가하였습니다.
- #54 CardView UI
- #55 Top Recent Events Networking (except Search)
- LIVE Pager Event Page View 추가
- Top Recent Events 데이터 Category별로 재 분류 추가

2019-02-15 06:43 UTC, kim-howard approved these changes
정말 신경을 많이 쓰신게 맞군요 ㅎㅎㅎ 몇가지만 확인 부탁드려요 ! 

💯

2019-02-15 06:43 UTC, onemoongit commented on tree/tree/Network Layer/Service/APIManager.swift
> +    ) -> Void) {
이렇게 하는게 더 낫지 않을까요?! 마치 fetchRecentEvents 자체가 void를 리턴한다라는 뜻 같네요 ( 실제로도 그렇지만 혼동의 여지가 생길 수 잇을 것 같아요 ! )
completion: @escaping (Result<Events>) -> Void
) { 

👍

2019-02-15 06:43 UTC, onemoongit commented on tree/tree/View/Live/TrendPageView.swift
> +        headerData.expanded = !headerData.expanded
단순히 true -> false , false -> true 를 원하는 거라면 
headerData.expanded.toggle() 을 사용해보는건 어떨까요?! 👍

2019-02-15 07:06 UTC, kimhyeri commented on tree/tree/View/Live/TrendPageView.swift
> +        headerData.expanded = !headerData.expanded
Swift4.2부터 나온 toggle() 편해여

2019-02-15 07:40 UTC, kimhyeri requested changes
고생 많으셨습니다!!!!!!!!!

2019-02-15 07:40 UTC, kimhyeri commented on tree/tree/View/Live/Keyword/TrendHeaderCell.swift
> +    weak var delegate: ExpandableHeaderDelegate?
개인적인 취향이지만 delegate보단 어떤 delegate인지 적어주는건 어떨까요?

2019-02-15 07:40 UTC, kimhyeri commented on tree/tree/View/Live/EventPageView.swift
> +            guard
위에 EventFeedCell 셀 검사하는 guard문이랑 합치는건 별로인가요?

2019-02-15 07:40 UTC, kimhyeri commented on tree/tree/View/Live/EventPageView.swift
> +            return 10
section0의 사이즈를 10을 한 이유가 위 navigation bar에 가까이 안 붙게 하기 위해 주신 거면테이블 뷰에 contentInset 주는건 어떨까요?

2019-02-15 13:38 UTC, yagom reviewed
👏

2019-02-15 13:38 UTC, yagom commented on tree/tree/Controller/Live/LiveViewController.swift
> +    private let trendPageNibName = "TrendPageView"
```swift
struct NibName {
    static let trendPage = "TrendPageView"
    static let eventPage = "EventPageView"
}
```
요건 어때요?

2019-02-15 13:38 UTC, yagom commented on tree/tree/View/Live/EventPageView.swift
> +        case 0:
section을 상수로 쓰기보다는 조금 더 의미있도록 enum을 사용해 보는건 어떨까요?

2019-02-15 13:38 UTC, yagom commented on tree/tree/View/Live/EventPageView.swift
> +                    return UITableViewCell()
셀을 만들어 주는 것보다 fatalError 혹은 precondition 등으로 적절히 종료시켜 주는 것도 방법입니다.
https://blog.yagom.net/561
코코님에게 한 번 물어보세요

2019-02-15 15:57 UTC, godpp commented on tree/tree/Network Layer/Service/APIManager.swift
> +    ) -> Void) {
오 좋은 의견인 것 같아요! 반영할게용 👍

2019-02-15 15:59 UTC, godpp commented on tree/tree/View/Live/TrendPageView.swift
> +        headerData.expanded = !headerData.expanded
몰랐던 내용이네요! 감사합니다 👍 👍 👍

2019-02-15 16:02 UTC, godpp commented on tree/tree/View/Live/Keyword/TrendHeaderCell.swift
> +    weak var delegate: ExpandableHeaderDelegate?
좋아여! 반영하겠습니다! 👍 👍

2019-02-15 16:04 UTC, godpp commented on tree/tree/View/Live/EventPageView.swift
> +            guard
움 튜터님이 말씀하신대로 리턴 값을 종료시키는 방향으로 간다면 구분하는 것이 맞는것 같아요!

의견 감사합니다! 👍 👍 👍

2019-02-15 16:06 UTC, godpp commented on tree/tree/View/Live/EventPageView.swift
> +            return 10
contentInset을 10을 준다면 section header도 contentInset에 포함되니 기존 위치보다 10만큼 내려서 붙지 않을까요?

2019-02-15 16:14 UTC, godpp commented on tree/tree/Controller/Live/LiveViewController.swift
> +    private let trendPageNibName = "TrendPageView"
가독성이 훨씬 좋아지는 것 같습니다!
+ XIB 사용이 많은만큼 쓰이는 곳 구분 없이 NibName들을 모아서 전역변수나 열거형으로 관리해도 좋은 방법이라고 할 수 있을까요??

2019-02-15 16:14 UTC, godpp commented on tree/tree/View/Live/EventPageView.swift
> +        case 0:
넵! 수정하도록 하겠습니다!

2019-02-15 16:17 UTC, godpp commented on tree/tree/View/Live/EventPageView.swift
> +                    return UITableViewCell()
네! 월요일에 자세히 물어보도록하겠습니다! 🤔

리뷰 감사합니다! 😊

2019-02-15 17:00 UTC, kimhyeri approved these changes

2019-02-15 23:24 UTC, yagom commented on tree/tree/Controller/Live/LiveViewController.swift
> +    private let trendPageNibName = "TrendPageView"
상황에 따라 다르겠지만 괜찮을 것 같아요

2019-02-15 23:28 UTC, yagom commented on tree/tree/Helper/Enum+FatalErrorMessage.swift
> +enum FatalErrorMessage: String {
오류는 Error라는 프로토콜을 따르면 됩니다.
https://developer.apple.com/documentation/swift/error
오류 내용을 설명하고 싶다면 localizedDescription을 구현하면 되구요
https://developer.apple.com/documentation/swift/error/2292912-localizeddescription

2019-02-16 06:34 UTC, godpp commented on tree/tree/Helper/Enum+FatalErrorMessage.swift
> +enum FatalErrorMessage: String {
넵! 수정하였습니다!!! 😊 감사합니다 :)

2019-02-16 07:19 UTC, yagom approved these changes

2019-02-16 07:25 UTC, merged