Feature/scrap tab detail 60
boostcamp3-iOS/team-a1 pull request #79
Opened 2019-02-15 07:31 UTC by onemoongit

다른 탭에서 사용할 수 있는 전반적인 기능을 추가했습니다
- 스크랩을 하고싶은 경우 아래와 같은 delegate 함수에서 customUIContextualAction를 리턴하면 됩니다.
```swift 
func tableView(
        _ tableView: UITableView,
        leadingSwipeActionsConfigurationForRowAt indexPath: IndexPath
    ) -> UISwipeActionsConfiguration? {
        //  . . . 코드를 확인해주세요
        let scrapAction = customUIContextualAction(.scrap, article, imagaData) { _ in }
        return UISwipeActionsConfiguration(actions: [scrapAction])
    }
```
- 스와이프 액션을 통해서 스크랩이 되었다면 스크랩을 뺄수 있는 버튼을 만들었습니다.

핵심기능을 우선순위로 두기 위해서 #60 에 남아있는 읽었는지 안읽었는지 확인하는 기능은 다음주에 구현할 예정입니다!
이제 Live Tab에서 web data를 받으면 이를 저장하는 기능을 만들겠습니다!

@kimhyeri papago 버튼 삭제 부탁드립니다.

2019-02-15 12:36 UTC, godpp requested changes
고생하셨습니다 👍 
주말도 퐈이팅입니다 👍 👍 👍

2019-02-15 12:36 UTC, godpp commented on tree/tree/Model/DataManager/ScrapManager.swift
> +        completion: @escaping (Bool,ScrappedArticle?) -> Void
completion handler가 closure일 경우 typealias로 정의하는 것이 좀 더 이해하기 좋을 것 같습니다! 👍

2019-02-15 12:36 UTC, godpp commented on tree/tree/Controller/Search/ArticleDetailViewController.swift
> +    private func setScrappedArticleData() {
set대신에 configure는 어떠신가요?? 🙂

2019-02-15 12:36 UTC, godpp commented on tree/tree/Extension/Extension+UITableViewDelegate.swift
> +    case delete
이 부분이 그때 true, false, nil인가요????

2019-02-15 12:36 UTC, godpp commented on tree/tree/Model/DataManager/ScrapManager.swift
> +            } else {
else 구문이 없어도 되지 않을까요??

2019-02-15 13:40 UTC, yagom reviewed
👏

2019-02-15 13:40 UTC, yagom commented on tree/tree/Controller/Scrap/ScrapViewController.swift
>      private var articleDeleted: Bool = false
is?

2019-02-15 15:00 UTC, kimhyeri approved these changes
굳굳 수고하셨습니당

2019-02-15 15:00 UTC, kimhyeri commented on tree/tree/Controller/Scrap/ScrapViewController.swift
> +
여기 부분에는 코드가 추가될 예정인가여?

2019-02-16 06:54 UTC, onemoongit commented on tree/tree/Extension/Extension+UITableViewDelegate.swift
> +    case delete
아니요 이 부분은 action 의 타입입니다!

2019-02-16 07:00 UTC, onemoongit commented on tree/tree/Model/DataManager/ScrapManager.swift
> +        completion: @escaping (Bool,ScrappedArticle?) -> Void
좋은 의견 감사합니다 !! 💯  역시 갓성준!

2019-02-16 07:26 UTC, onemoongit commented on tree/tree/Controller/Scrap/ScrapViewController.swift
> +
넵 아직 추가되지 않았습니다 ㅎㅎㅎㅎ

2019-02-16 07:26 UTC, onemoongit commented on tree/tree/Model/DataManager/ScrapManager.swift
> +            } else {
empty 인경우 completion(false,nil) 그렇지 않은 경우 completion(true,result.first) 입니다.
왜 else가 없어도 괜찮다고 생각하신건가요?! @godpp ❓

2019-02-16 07:26 UTC, onemoongit commented on tree/tree/Controller/Search/ArticleDetailViewController.swift
> +    private func setScrappedArticleData() {
👍

2019-02-16 07:26 UTC, onemoongit commented on tree/tree/Controller/Scrap/ScrapViewController.swift
>      private var articleDeleted: Bool = false
수정하겠습니다!! 👍

2019-02-16 07:34 UTC, yagom commented on tree/tree/Controller/Scrap/ScrapViewController.swift
> +    private var articleIsDeleted: Bool = false
isArticleDeleted가 맞지 않을까요?
@kimhyeri @godpp 는 어떻게 생각하나요?

2019-02-16 07:35 UTC, onemoongit commented on tree/tree/Controller/Scrap/ScrapViewController.swift
> +    private var articleIsDeleted: Bool = false
저도 처음에 그렇게 썼다가 뭔가 이상해서 articleIsDeleted로 변경했습니다하하핳

2019-02-16 07:44 UTC, yagom approved these changes

2019-02-16 07:52 UTC, godpp commented on tree/tree/Model/DataManager/ScrapManager.swift
> +            } else {
앗 비동기 처리라 else 없으면 둘 다 찍히겠군용 👍 👍 👍

2019-02-16 07:52 UTC, godpp approved these changes

2019-02-16 07:54 UTC, merged