Feature/search
boostcamp3-iOS/team-a1 pull request #81
Opened 2019-02-16 08:10 UTC by kimhyeri

- webView 연결 작업했습니다. (분기 처리는 아직 안되어있어요.)
- article 내용 추출하는 extractArticle함수 만들었습니다.
- 소소한 버그들 해결하고 기획이 변경되어 필요없는 코드는 제거했습니다.

2019-02-16 08:33 UTC, godpp requested changes
고생하셨습니당 👍 👍 👍

2019-02-16 08:33 UTC, godpp commented on tree/tree/Controller/Search/ArticleWebViewController.swift
> +    var articleURL: String = ""
Optional이 좋지 않을까요? 🤔세이프하지 못한 상황이 올 수도 있을 것 같아용

2019-02-16 08:33 UTC, godpp commented on tree/tree/Controller/Search/ArticleWebViewController.swift
> +    private func makeRequestURL(urlString: String) -> URLRequest? {
리턴이 URLRequest이니 makeURLRequest가 좋을 것 같아용! 👍

2019-02-16 08:33 UTC, godpp commented on tree/tree/Controller/Search/SearchViewController.swift
> +    private func setuppDelegate() {
pp 오타 👍

2019-02-16 08:33 UTC, godpp commented on tree/tree/Controller/Search/SearchViewController.swift
> +        if let getSearchKeyword = searchBar.text, getSearchKeyword.count > 0, !isLoading {
, 기준 내려주세용 👍

2019-02-16 08:33 UTC, godpp commented on tree/tree/Network Layer/Service/APIManager.swift
> +        ) -> Void) {
현태님이 ) -> Void 위로 올리자고 하셔서 수정됐어용!

2019-02-16 08:35 UTC, kimhyeri commented on tree/tree/Controller/Search/SearchViewController.swift
> +    private func setuppDelegate() {
pp...수정하겠습니다.

2019-02-16 08:36 UTC, kimhyeri commented on tree/tree/Controller/Search/SearchViewController.swift
> +        if let getSearchKeyword = searchBar.text, getSearchKeyword.count > 0, !isLoading {
앗 넵!

2019-02-16 08:37 UTC, kimhyeri commented on tree/tree/Controller/Search/ArticleWebViewController.swift
> +    private func makeRequestURL(urlString: String) -> URLRequest? {
네 수정하겠습니다! 감사합니다!

2019-02-16 08:39 UTC, kimhyeri commented on tree/tree/Network Layer/Service/APIManager.swift
> +        ) -> Void) {
네 그때 함수 자체가 void를 리턴한다고 생각할 수 있다 한 거! 오케이

2019-02-16 08:44 UTC, kimhyeri commented on tree/tree/Controller/Search/ArticleWebViewController.swift
> +    var articleURL: String = ""
밑에서 걸러내긴 하는데 Optional이 더 좋을 것 같네요 !

2019-02-16 08:48 UTC, godpp approved these changes

2019-02-16 08:48 UTC, kim-howard requested changes
수고하셨습니다 몇가지 코멘트 확인 부탁드려요! 🥇

2019-02-16 08:48 UTC, onemoongit commented on tree/tree/Helper/ImageHelper/ImageCache.swift
> +        let directory = FileManager.default.urls(for: .cachesDirectory, in: .userDomainMask).first
👍

2019-02-16 08:48 UTC, onemoongit commented on tree/tree/Controller/Search/SearchFilterViewController.swift
> +            let language = findSelectedRow(row: languageLabel.text ?? "Eng") {
저번에 야곰님께 Review 받았던 링크 기억하시나요?
https://medium.com/marojuns-ios/swift-%EC%BB%B4%ED%8C%8C%EC%9D%BC-%EC%86%8D%EB%8F%84%EB%A5%BC-%ED%96%A5%EC%83%81%EC%8B%9C%ED%82%A4%EC%9E%90-51617509e35
한번 다시 살펴보시면 좋을 것 같습니다 !! Nil-Coalescing operator 제거 부탁드려요!

2019-02-16 08:48 UTC, onemoongit commented on tree/tree/Controller/Search/ArticleWebViewController.swift
> +    private func setLoadingView() {
여기도 setup 이 들어가야 하지 않을까요?! 👍

2019-02-16 08:51 UTC, kimhyeri commented on tree/tree/Controller/Search/ArticleWebViewController.swift
> +    private func setLoadingView() {
좋습니다! 감사합니다!

2019-02-16 09:02 UTC, kimhyeri commented on tree/tree/Controller/Search/SearchFilterViewController.swift
> +            let language = findSelectedRow(row: languageLabel.text ?? "Eng") {
네, 저는 스위프트의 특징인 옵셔널 값을 다루기 위한 연산자 ??이 코드가 간결해지고 편해서 좋았는데,, 링크에 nil coalescing?? 연산을 피하자고 되어있길래 찾아보니 nil-coalescing 연산자를 사용할 때마다 옵션에 어떤 값이 있는지에 상관없이 기본값을 계산해야하고 기본값의 계산은 디스크 메모리로부터 과도한 읽기 연산 일 수 있다고 하네요. 오버 헤드가 발생할 수 있기 때문에 ?? nil coalescing연산을 피하는게 좋다니 이 부분은 수정하도록 하겠습니다! 좋은 의견 감사합니다!

2019-02-16 09:23 UTC, kim-howard approved these changes

2019-02-17 08:51 UTC, yagom reviewed
잘 했습니다~ 몇몇 간단한 코멘트만 남겨뒀어요~

2019-02-17 08:51 UTC, yagom commented on tree/tree/Controller/Search/ArticleViewer/ArticleWebViewController.swift
> +    @IBAction func backButtonItem(_ sender: UIBarButtonItem) {
이름을 다시 생각해 보면 좋겠어요~

2019-02-17 08:51 UTC, yagom commented on tree/tree/Controller/Search/SearchFilterViewController.swift
> +    private func findSelectedRow(row: String) -> String? {
무슨 역할을 하는지 이름으로 파악하기가 어려운 것 같아요. 매개변수 이름도 마찬가지구요.

2019-02-17 08:51 UTC, yagom commented on tree/tree/Extension/Extension+PickerView.swift
>      func getList() -> [String] {
이름을 다시 생각해 봅시다

2019-02-17 08:51 UTC, yagom commented on tree/tree/Network Layer/API/ExtractAPI.swift
> +enum ExtractAPI {
👍

2019-02-17 08:51 UTC, yagom commented on tree/tree/Network Layer/API/ExtractAPI.swift
> +        guard let url = URL(string: "http://analytics.eventregistry.org") else { fatalError("Invalid URL") }
기본 주소도 상수 등으로 빼주는건 어떨까요?

2019-02-17 09:35 UTC, kimhyeri commented on tree/tree/Network Layer/API/ExtractAPI.swift
> +        guard let url = URL(string: "http://analytics.eventregistry.org") else { fatalError("Invalid URL") }
네! 모든 API에 사용되는 기본 주소들을 별도의 스위프트 파일에 모아서 사용하겠습니다!

2019-02-17 09:37 UTC, kimhyeri commented on tree/tree/Extension/Extension+PickerView.swift
>      func getList() -> [String] {
pickerItemList()으로 변경해보겠습니다 !

2019-02-17 09:37 UTC, kimhyeri commented on tree/tree/Controller/Search/ArticleViewer/ArticleWebViewController.swift
> +    @IBAction func backButtonItem(_ sender: UIBarButtonItem) {
backButtonItemDidTap으로 변경하겠습니다!

2019-02-17 09:45 UTC, kimhyeri commented on tree/tree/Controller/Search/SearchFilterViewController.swift
> +    private func findSelectedRow(row: String) -> String? {
네 extractUserSelectedLanguage(selectedItem: String)으로 변경하겠습니다!

2019-02-17 11:01 UTC, yagom approved these changes
좋아요~~ 고생했습니다~ 코멘트 하나 확인!

2019-02-17 11:01 UTC, yagom commented on tree/tree/Helper/BaseURL.swift
> +let extractAPIBaseURL = "http://analytics.eventregistry.org"
```swift
struct BaseURL {
    static let extractAPI = "http://analytics.eventregistry.org"
    static let naverAPI = "https://openapi.naver.com/v1/datalab/search"
    //...
}
```
요렇게는 어때요?

2019-02-17 11:14 UTC, kimhyeri commented on tree/tree/Helper/BaseURL.swift
> +let extractAPIBaseURL = "http://analytics.eventregistry.org"
헉 훨씬 좋은 것 같아요 ! 수정했습니다 감사합니다 ! 😁

2019-02-17 12:18 UTC, merged