Feature/siri
boostcamp3-iOS/team-a1 pull request #85
Opened 2019-02-17 11:05 UTC by godpp

SiriKit

* 현재 급상승 검색어 국가별로 보여줄 수 있는 Siri Shortcut 추가 했습니다.
* @kimhyeri 님 개발자 계정을 사용하였고, tree, TrendIntent, TrendIntentUI Target 모두 혜리님 계정사용해야 합니다.
* Network Layer와 연동하는 부분에서 Intent Target을 추가해야하는데 사이드 이펙트가 (많이) 발생하여 추후에 Network Layer 부분만 Framework로 만들어야 할 것 같습니다... (tree - Network Layer - Intent) 
* 추가로 다른 부분도 연동해볼 예정입니다.

2019-02-17 11:30 UTC, kimhyeri requested changes
Siri 진짜 신기하네요 ! 새로운 도전 하신거 굳 !!!!!
성준님한테 배워서 다음에 저도 써봐야겠어요

코멘트 몇가지 확인 부탁드려요 !!!!

2019-02-17 11:30 UTC, kimhyeri commented on tree/TrendUI/IntentViewController.swift
> +    ) -> Void) {
요거 올리기로 했어요 !

2019-02-17 11:30 UTC, kimhyeri commented on tree/TrendUI/IntentViewController.swift
> +        var siriResponseViewSize = self.extensionContext!.hostedViewMaximumAllowedSize
guard로 extensionContext있는지 확인해주는건 어떨까요?

2019-02-17 11:30 UTC, kimhyeri commented on tree/TrendUI/IntentViewController.swift
> +        cell.rankLabel.text = "\(indexPath.row + 1)"
데이터 넣는 작업은 TrendIntentCell에서 해주는건 어떨까요?

2019-02-17 11:30 UTC, kimhyeri commented on tree/tree/Controller/Live/LiveViewController.swift
> +    private func donate(country: String) {
기본 제공되는 함수명이 donate라니 .. 신기하네요 ..

2019-02-17 11:38 UTC, godpp commented on tree/TrendUI/IntentViewController.swift
> +        cell.rankLabel.text = "\(indexPath.row + 1)"
오 테스트하다가 까먹었군요! 감사합니다 👍

2019-02-17 11:41 UTC, godpp commented on tree/tree/Controller/Live/LiveViewController.swift
> +    private func donate(country: String) {
(저도 왜 donate인지 모르겠는...)

INInteraction을 보면 요렇게 쓰이더라구용
```swift
    // donate this interaction to the system
    open func donate(completion: ((Error?) -> Void)? = nil)
```

2019-02-17 11:46 UTC, godpp commented on tree/TrendUI/IntentViewController.swift
> +        var siriResponseViewSize = self.extensionContext!.hostedViewMaximumAllowedSize
항상 있을 수 밖에 없긴 한데 안전하게 바꾸겠습니당 👍 👍 👍

2019-02-17 11:48 UTC, godpp commented on tree/TrendUI/IntentViewController.swift
> +    ) -> Void) {
가릿가릿! 👍 

*  configureView 메소드가 기본제공이길래 completion handler는 일단 typealias로 빼진 않았습니당

2019-02-17 12:06 UTC, kimhyeri commented on tree/tree/Controller/Live/LiveViewController.swift
> +    private func donate(country: String) {
찾아보니까  
`“Donating” an Intent means providing Siri with the information it needs to make a suggestion for an action that the user just completed.` 
Siri가 필요한 정보를 제공한다는 뉘앙스로는 donate도 이상하진 않은 것 같네요.

2019-02-17 12:19 UTC, yagom reviewed
시리! 좋은시도 멋집니다

2019-02-17 12:19 UTC, yagom commented on tree/Trend/IntentHandler.swift
> +    override func handler(for intent: INIntent) -> Any {
intent를 꼭 받아와야 할 필요가 있나요? 받아온 intent는 타입확인에만 쓰이는 것 같은데 이 메서드의 활용 용도를 잘 모르겠습니다

2019-02-17 12:19 UTC, yagom commented on tree/TrendUI/IntentViewController.swift
> +            self.activityIndicator.stopAnimating()
https://developer.apple.com/documentation/uikit/uiactivityindicatorview/1622837-hideswhenstopped
인디케이션 생성시 이 프로퍼티를 설정해두면 굳이 stop을 할 필요가 없을 것 같아요~

2019-02-17 12:19 UTC, yagom commented on tree/tree/Controller/Live/LiveViewController.swift
> +        print(geo)
print

2019-02-17 12:19 UTC, yagom commented on tree/tree/Controller/Live/LiveViewController.swift
> +                print("권한이 거부됨.")
거부된 권한을 사용자에게 보여줄 필요는 없나요?

2019-02-17 12:26 UTC, godpp commented on tree/Trend/IntentHandler.swift
> +    override func handler(for intent: INIntent) -> Any {
IntentsExtension 기본 메소드에서 여러 기능들을 처리해주는 다른 handler로 분기 시켜주기 위해 활용하였습니다.
* 다른 intent들이 추가 된다면 분기 처리를 해줘야 할 것 같아 타입 확인을 했습니다.
* 최근 주요 이슈 또는 스크랩 한 뉴스 기사를 불러올 수 있는 다른 handler를 추가할 계획입니다.

2019-02-17 12:27 UTC, godpp commented on tree/tree/Controller/Live/LiveViewController.swift
> +        print(geo)
삭제하도록 하겠습니다...! 👍

2019-02-17 12:30 UTC, godpp commented on tree/TrendUI/IntentViewController.swift
> +            self.activityIndicator.stopAnimating()
넵! 사용해보겠습니다! 😄

2019-02-17 12:32 UTC, yagom commented on tree/Trend/IntentHandler.swift
> +    override func handler(for intent: INIntent) -> Any {
그렇군요

2019-02-17 12:50 UTC, kimhyeri approved these changes

2019-02-17 13:08 UTC, godpp commented on tree/tree/Controller/Live/LiveViewController.swift
> +                print("권한이 거부됨.")
case문 모두 작성하여 Alert 창으로 안내문 띄우겠습니다!

코멘트 감사합니다! 😄

2019-02-18 03:28 UTC, kim-howard approved these changes
Siri 아주 멋지네요 ! 앱의 생명력을 불어넣으신것 같아요 ! 👍

2019-02-18 05:04 UTC, yagom approved these changes
👍

2019-02-18 05:50 UTC, merged