Feature/splash
boostcamp3-iOS/team-a1 pull request #90
Opened 2019-02-18 06:52 UTC by godpp

Animation 같이 추가했습니다.

* 4개의 원이 순서대로 ScaleUp을 구현했고
* App Name Label은 FadeIn을 구현했습니다.

2019-02-18 07:24 UTC, kimhyeri reviewed
고생하셨슴다 ~~~~~~~~~~!~!~!~1

2019-02-18 07:24 UTC, kimhyeri commented on tree/tree/Extension/Extension+UIView.swift
> +    func applyGradient(colours: [UIColor], startPoint: CGPoint, endPoint: CGPoint) {
이렇게 따로 빼신거 좋네요 !

2019-02-18 07:24 UTC, kimhyeri commented on tree/tree/Controller/Splash/SplashViewController.swift
> +    private let orangePurpleBlueGradientColors = [UIColor.orange, UIColor.purpleBlue]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ이름에 모든게 담겨있네요

2019-02-18 07:50 UTC, godpp commented on tree/tree/Controller/Splash/SplashViewController.swift
> +    private let orangePurpleBlueGradientColors = [UIColor.orange, UIColor.purpleBlue]
좋은 아이디어 있으신가요?... ㅜㅜ  HELPED WANTED! ㅋㅋㅋㅋ

2019-02-18 07:50 UTC, godpp commented on tree/tree/Extension/Extension+UIView.swift
> +    func applyGradient(colours: [UIColor], startPoint: CGPoint, endPoint: CGPoint) {
👍  감사합니당 👍

2019-02-18 07:56 UTC, kim-howard requested changes
오타 하나만 수정해주세요 ^^ ! 수고하셨습니다 💯

2019-02-18 07:56 UTC, onemoongit commented on tree/tree/Controller/Splash/SplashViewController.swift
> +    private let orangePurpleBlueGradientColors = [UIColor.orange, UIColor.purpleBlue]
제 생각에는 어떤 원을 위한 gradient color인지 말해주는게 낫지 않을까요? 예를들어서 rightupBallGradientColors 라던지?!

2019-02-18 07:56 UTC, onemoongit commented on tree/tree/Controller/Splash/SplashViewController.swift
> +    private func changerRootViewController() {
Rr 오타 있네요!!

2019-02-18 07:56 UTC, onemoongit commented on tree/tree/Controller/Splash/SplashViewController.swift
> +            withIdentifier: "ScrapTabBarController"
@kimhyeri 같이 나중에 ScrapTabBarController는 변경하는것이 좋을 것 같습니다 예를 들어서 MainTabBarController 라던지요!
다만 ScrapViewController에 연결된것이 있어서 한번 확인해봐야할것 같네요! 😄

2019-02-18 07:56 UTC, onemoongit commented on tree/tree/Extension/Extension+UIView.swift
> +    func applyGradient(colours: [UIColor], startPoint: CGPoint, endPoint: CGPoint) {
👍

2019-02-18 08:33 UTC, godpp commented on tree/tree/Controller/Splash/SplashViewController.swift
> +            withIdentifier: "ScrapTabBarController"
네! 알겠습니당 👍

2019-02-18 08:34 UTC, godpp commented on tree/tree/Controller/Splash/SplashViewController.swift
> +    private func changerRootViewController() {
앗... 수정하겠습니다!

2019-02-18 08:35 UTC, godpp commented on tree/tree/Controller/Splash/SplashViewController.swift
> +    private let orangePurpleBlueGradientColors = [UIColor.orange, UIColor.purpleBlue]
rightBottomGradientColors 어떠신가요!

2019-02-18 08:40 UTC, kim-howard approved these changes

2019-02-18 08:56 UTC, yagom commented on tree/tree/Controller/Splash/SplashViewController.swift
> +    private func animateObjectToScaleUp(_ object: UIView, _ delay: TimeInterval) {
매개변수 레이블을 굳이 없앤 이유가 있을까요? 호출하는 입장에서는 두 번째 파라메터로 무엇을 넘겨줘야 할지 감이 잘 오지 않을 것 같아요
그리고 첫 번째 파라메터도 Object라고 되어 있는데 실질적으로는 UIView가 들어오네요. 혼란의 여지가 있지 않을까합니다

2019-02-18 08:58 UTC, godpp commented on tree/tree/Controller/Splash/SplashViewController.swift
> +    private func animateObjectToScaleUp(_ object: UIView, _ delay: TimeInterval) {
앗 이전에 UILabel도 인자로 받아 사용했었기에 object란 이름이 더 맞는 것 같아서 사용했었습니다!
수정하겠습니다! 😄

코멘트 감사합니다! 😊

2019-02-18 09:06 UTC, kimhyeri approved these changes

2019-02-18 09:11 UTC, yagom approved these changes

2019-02-19 04:22 UTC, godpp commented
Merge 과정에서 project.xcdoeproj 파일 충돌이 해결되지 않아 Refacting 된 코드로 PR 다시 날리겠습니다.

2019-02-19 04:22 UTC, closed without merging